version: '3.1'

services:

    mongodb:
        image: mongo:5.0-focal
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root

        ports:
          - 27017:27017
