name: check-application

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2

            - name: Run Tests
              run: cargo test --verbose

            - name: Build Application
              run: cargo build --verbose
